version: '3.3'
services:
  dbsetup:
    depends_on:
    - mssql
    build:
      context: .
      dockerfile: Dockerfile-dbsetup
    environment:
      TRAM_DB_SERVER: "mssql"
      TRAM_SA_PASSWORD: "TestPa$$word"
      TRAM_DB: "TramDb"
      TRAM_SCHEMA: "eventuate"
      TRAM_SCHEMA2: "schema1"
  eventuatetramtests:
    depends_on:
    - zookeeper
    - kafka
    - mssql
    - cdcservice1
    - cdcservice2
    build: .
    environment:
      KafkaBootstrapServers: "kafka:29092"
      ConnectionStrings__EventuateTramDbConnection: "Server=mssql;Database=TramDb;User Id=sa;Password=TestPa$$word"
    volumes:
    - ./bin/Release/netcoreapp2.2/publish:/app
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  cdcservice1:
    image: eventuateio/eventuate-tram-cdc-mysql-service:${CDC_SERVICE_DOCKER_VERSION}
    depends_on:
    - kafka
    - mssql
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql;databaseName=TramDb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: TestPa$$word
      SPRING_DATASOURCE_TEST_ON_BORROW: "true"
      SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver

      SPRING_PROFILES_ACTIVE: EventuatePolling

      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

      EVENTUATE_DATABASE_SCHEMA: eventuate

      EVENTUATELOCAL_CDC_POLLING_INTERVAL_IN_MILLISECONDS: 500
      EVENTUATELOCAL_CDC_MAX_EVENTS_PER_POLLING: 1000
      EVENTUATELOCAL_CDC_MAX_ATTEMPTS_FOR_POLLING: 100
      EVENTUATELOCAL_CDC_POLLING_RETRY_INTERVAL_IN_MILLISECONDS: 500

      EVENTUATELOCAL_CDC_READER_NAME: Reader1
      EVENTUATELOCAL_CDC_LEADERSHIP_LOCK_PATH: /eventuatelocal/cdc/leader/1
  cdcservice2:
    image: eventuateio/eventuate-tram-cdc-mysql-service:${CDC_SERVICE_DOCKER_VERSION}
    depends_on:
    - kafka
    - mssql
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql;databaseName=TramDb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: TestPa$$word
      SPRING_DATASOURCE_TEST_ON_BORROW: "true"
      SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver

      SPRING_PROFILES_ACTIVE: EventuatePolling

      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

      EVENTUATE_DATABASE_SCHEMA: schema1

      EVENTUATELOCAL_CDC_POLLING_INTERVAL_IN_MILLISECONDS: 500
      EVENTUATELOCAL_CDC_MAX_EVENTS_PER_POLLING: 1000
      EVENTUATELOCAL_CDC_MAX_ATTEMPTS_FOR_POLLING: 100
      EVENTUATELOCAL_CDC_POLLING_RETRY_INTERVAL_IN_MILLISECONDS: 500

      EVENTUATELOCAL_CDC_READER_NAME: Reader2
      EVENTUATELOCAL_CDC_LEADERSHIP_LOCK_PATH: /eventuatelocal/cdc/leader/2
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      SA_PASSWORD: "TestPa$$word"
      ACCEPT_EULA: "Y"
      MSSQL_MEMORY_LIMIT_MB: "500"
