name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/ge-digital-firestorm/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build
      run: ./build.sh
      env:
        PACKAGE_ID: ${{secrets.PACKAGE_ID}}
    - name: Upload bin folder
      uses: actions/upload-artifact@v1
      with:
        name: bin
        path: IO.Eventuate.Tram/bin

    - name: Unit Tests
      run: dotnet test -c Release --no-build --verbosity normal --logger trx IO.Eventuate.Tram.UnitTests/
    - name: Upload unit test results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: unit-test-results
        path: IO.Eventuate.Tram.UnitTests/TestResults
 
    - name: Integration Tests
      run: ./test.sh
      working-directory: ./IO.Eventuate.Tram.IntegrationTests
      env:
        CDC_SERVICE_DOCKER_VERSION: 0.21.3.RELEASE
    - name: Upload integration test results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: integration-test-results
        path: IO.Eventuate.Tram.IntegrationTests/bin/Release/netcoreapp3.1/TestResults

#    - name: Publish nuget package
#      run: dotnet nuget push IO.Eventuate.Tram/bin/Release/*.nupkg