name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet build -c Release
    - name: Pack
      run: dotnet pack -c Release
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: bin
        path: IO.Eventuate.Tram/bin
    - name: Unit Tests
      run: dotnet test -c Release --no-build --verbosity normal IO.Eventuate.Tram.UnitTests/
    - name: Integration Tests
      run: ./test.sh
      working-directory: ./IO.Eventuate.Tram.IntegrationTests
      env:
        CDC_SERVICE_DOCKER_VERSION: 0.21.3.RELEASE
